### ISSUE TITLE
Inspect existing triggers

### ISSUE THREAD

**Issue by Ovid** [miyagawa/Class-Trigger#1]
Hi @miyagawa !

We've a client who uses `Class::Trigger` in some fairly important, low-level code. Due to trigger ordering, they have one trigger which must be:

1. Set once and only once
2. Called before all other triggers

Doing this could be as simple as:

```perl
$object->call_trigger('unique_trigger');
$object->call_trigger('regular_trigger'); # all the other triggers
```

However, when we call `add_trigger($label)`, I don't see a clean way of knowing if someone has already added a trigger for `$label`. What would be nice is to have a `has_trigger` method:

```perl
if ( $object->has_trigger($label) ) {
    # warn/die/croak/whatever
}
else {
    $object->add_trigger($label, $sub);
}
```

Unfortunately, that would add a new method to all classes which use this mixin.

**Comment by Ovid** [comment]
Actually, let me amend the above. We would need `add_unique_trigger`, too. The rest of the `Class::Trigger` code would need to be updated to ensure someone can't sneakily call `add_trigger` elsewhere.

If this behavior doesn't seem generic enough to warrant in inclusion with `Class::Trigger`, I totally understand. We can handle it on our end, but that likely means forking this module.

**Comment by miyagawa** [comment]
> If this behavior doesn't seem generic enough to warrant in inclusion with Class::Trigger, I totally understand.

Agreed, it sounds like a special use case that I haven't heard for as long as I maintain this module. To be honest i consider this module to be feature complete and I'm not interested in enhancing the functionalities.

> that likely means forking this module.

That sounds like the way to go.
